#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpicxx 2DWave_vert_nd.cpp  -o 2DWave_exe
mpicxx 2DWave_hor.cpp -o 2DWave_eve
mpicxx 2DWave_hor_nd -o 2DWave_exe

## remove object files if there is any!:
# rm *.mod
# rm *.o

